### ISSUE TITLE
[background_locator_2: 2.0.6] App crashes when "startLocator()" in release mode

### ISSUE THREAD

**Issue by lcarielo** [Yukams/background_locator_fixed#102]
The library in "release" mode fails, in "debug" mode it works correctly. I have only tested on an Android device.
Any solution?

background_locator_2: ^2.0.6
Flutter: 3.13.2
Dart: 3.1.0
BuildGradle: 8.1.1
Android: 11

Issue:
```
E/AndroidRuntime(18658): FATAL EXCEPTION: main
E/AndroidRuntime(18658): Process: com.luis.carielo.my_back_locator_app, PID: 18658
E/AndroidRuntime(18658): java.lang.RuntimeException: Unable to start service yukams.app.background_locator_2.IsolateHolderService@6a7c267 with Intent { act=START cmp=com.luis.carielo.my_back_locator_app/yukams.app.background_locator_2.IsolateHolderService (has extras) }: java.lang.RuntimeException: Missing type parameter.
E/AndroidRuntime(18658): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4526)
E/AndroidRuntime(18658): 	at android.app.ActivityThread.access$2200(ActivityThread.java:263)
E/AndroidRuntime(18658): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2095)
E/AndroidRuntime(18658): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(18658): 	at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(18658): 	at android.app.ActivityThread.main(ActivityThread.java:8097)
E/AndroidRuntime(18658): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(18658): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(18658): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
E/AndroidRuntime(18658): Caused by: java.lang.RuntimeException: Missing type parameter.
E/AndroidRuntime(18658): 	at o3.a.d(SourceFile:1)
E/AndroidRuntime(18658): 	at o3.a.<init>(SourceFile:1)
E/AndroidRuntime(18658): 	at yukams.app.background_locator_2.d$a$a.<init>(Unknown Source:0)
E/AndroidRuntime(18658): 	at yukams.app.background_locator_2.d$a.b(SourceFile:1)
E/AndroidRuntime(18658): 	at x4.d.a(SourceFile:1)
E/AndroidRuntime(18658): 	at yukams.app.background_locator_2.IsolateHolderService.s(SourceFile:1)
E/AndroidRuntime(18658): 	at yukams.app.background_locator_2.IsolateHolderService.t(SourceFile:1)
E/AndroidRuntime(18658): 	at yukams.app.background_locator_2.IsolateHolderService.onStartCommand(Unknown Source:118)
E/AndroidRuntime(18658): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4503)
E/AndroidRuntime(18658): 	... 8 more
```

**Comment by mhd-ghaith-abtah** [comment]
did you find any solution?

**Comment by B3K4682** [comment]
Hello, did you find any solution for this? I have the same issue

**Comment by hpsolver** [comment]
Did anyone find any solutions ?

**Comment by B3K4682** [comment]
@hpsolver 

The issue you're encountering might be related to "TypeToken." This solution worked for me: https://github.com/Yukams/background_locator_fixed/issues/137#issuecomment-2382695346

**Comment by rmf11048** [comment]
This fixed my issue! thanks!

> [@hpsolver](https://github.com/hpsolver)
> 
> The issue you're encountering might be related to "TypeToken." This solution worked for me: [#137 (comment)](https://github.com/Yukams/background_locator_fixed/issues/137#issuecomment-2382695346)
