### ISSUE TITLE
Background location tracker crashes in Android 14

### ISSUE THREAD

**Issue by Karuppasamy-M** [Yukams/background_locator_fixed#139]
### **Manifest :** 

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.ACCESS_NOTIFICATION_POLICY" />
    <uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS"/>
    <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS"/>
    <uses-permission android:name="an.ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS"/>
    <uses-permission android:name="android.permission.NOTIFICATION_POLICY_ACCESS_SETTINGS" />
    <uses-permission android:name="android.permission.USE_EXACT_ALARM" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />

    <application
        android:label="{appLabelName}"
        android:name="${applicationName}"
        android:icon="@mipmap/ic_launcher">

       <activity
            android:name=".MainActivity"
            android:exported="true"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:usesCleartextTraffic="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        
        </activity>
        
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

        <receiver android:name="yukams.app.background_locator_2.BootBroadcastReceiver"
            android:exported="false"
            android:enabled="true">
            <intent-filter>
                <action android:name="android.intent.action.BOOT_COMPLETED"/>
            </intent-filter>
        </receiver>
        <service
            android:name="yukams.app.background_locator_2.IsolateHolderService"
            android:permission="android.permission.FOREGROUND_SERVICE"
            android:exported="false"
            android:stopWithTask="false"
            android:foregroundServiceType = "location"
            />
       
    </application>

### Crash Details : 

**I received these crash details from the google play console specifically for android.**

  **yukams.app.background_locator_2.IsolateHolderService.onCreate
java.lang.SecurityException**

Exception java.lang.RuntimeException:
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4777)
  at android.app.ActivityThread.-$$Nest$mhandleCreateService
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2356)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:205)
  at android.os.Looper.loop (Looper.java:294)
  at android.app.ActivityThread.main (ActivityThread.java:8391)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:640)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:995)
Caused by java.lang.SecurityException:
  at android.os.Parcel.createExceptionOrNull (Parcel.java:3057)
  at android.os.Parcel.createException (Parcel.java:3041)
  at android.os.Parcel.readException (Parcel.java:3024)
  at android.os.Parcel.readException (Parcel.java:2966)
  at android.app.IActivityManager$Stub$Proxy.setServiceForeground (IActivityManager.java:6914)
  at android.app.Service.startForeground (Service.java:775)
  at yukams.app.background_locator_2.IsolateHolderService.onCreate (IsolateHolderService.java)
  at android.app.ActivityThread.handleCreateService (ActivityThread.java:4764)
Caused by android.os.RemoteException: Remote stack trace:
  at com.android.server.am.ActiveServices.validateForegroundServiceType (ActiveServices.java:2734)
  at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked (ActiveServices.java:2445)
  at com.android.server.am.ActiveServices.setServiceForegroundLocked (ActiveServices.java:1792)
  at com.android.server.am.ActivityManagerService.setServiceForeground (ActivityManagerService.java:13685)
  at android.app.IActivityManager$Stub.onTransact (IActivityManager.java:3458)

**Comment by TechBoyy6** [comment]
same

**Comment by nicoloso100** [comment]
Adding 
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE_LOCATION" />`
Worked for me:
https://stackoverflow.com/questions/76943771/foreground-service-crashing-on-android-14

**Comment by rubiaservices** [comment]
same with me

`Caused by: android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{f542e5b 24952:com.rubia.driver/u0a440} targetSDK=34
E/AndroidRuntime(24952): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
E/AndroidRuntime(24952): 	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)`

**Comment by dhiaCodes** [comment]
For those who still have the Android 14 crash, I believe my fork may be helpful: https://github.com/dhiaCodes/background_locator_fixed.git
@Karuppasamy-M 
@TechBoyy6 
@rubiaservices 
@Yukams
