### ISSUE TITLE
[Android] How to use flutter packages on the background locator service?

### ISSUE THREAD

**Issue by hieudz** [Yukams/background_locator_fixed#25]
How can we use other packages on the background locator service?

I tried
```
static void callbackFromBackground(LocationDto locationDto) async {
    LocationPermissionStatus? status = await LocationPermissionHandler.getLocationPermission();
    ....
 }
 ```
 Where `getLocationPermission()` implementation is:
 ```
 static Future<LocationPermissionStatus> getLocationPermission() async {
    var serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (serviceEnabled) {
      var permission = await Geolocator.checkPermission();
      return LocationPermissionStatus(
        appLocationPermission: permission,
        isLocationServiceEnabled: true,
      );
    }
    var permission = await Geolocator.checkPermission();
    return LocationPermissionStatus(
      appLocationPermission: permission,
      isLocationServiceEnabled: true,
    );
  }
  ```
 But it raise error, which seems like because we can't use packages on the isolate
```
 E/flutter (22736): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method isLocationServiceEnabled on channel flutter.baseflow.com/geolocator)
E/flutter (22736): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175:7)
E/flutter (22736): <asynchronous suspension>
E/flutter (22736): #1      LocationPermissionHandler.getLocationPermission (package:aye_app/service/permission/location_permission_handler.dart:98:26)
E/flutter (22736): <asynchronous suspension>
E/flutter (22736): #2      BackgroundLocationService.callbackFromBackground (package:aye_app/service/location/background_location_service.dart:56:46)
E/flutter (22736): <asynchronous suspension>
```

**Comment by archsmilson** [comment]
If your problem is occuring on IOS, the wiki describes how to register other packages for the background callback:

https://github.com/Yukams/background_locator_fixed/wiki/Use-other-plugins-in-callback

**Comment by Yukams** [comment]
Hi @hieudz can you please try this https://github.com/flutter/flutter/issues/99155#issuecomment-1060956399

**Comment by hieudz** [comment]
It works!!

Thank you for your help
