### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: is a regular instance: Instance of 'LocationDto'

### ISSUE THREAD

**Issue by jesussmile** [Yukams/background_locator_fixed#57]
Hi, so i have upgraded gradle and these are my settings.
**android/build.gradle**
```
buildscript {
    ext.kotlin_version = '1.7.10'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.0'
        classpath 'com.google.gms:google-services:4.3.8'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}
```
Then on **android/gradle/wrapper/gradle-wrapper.properties**
```
#Fri Jun 23 08:50:38 CEST 2017
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip
```

Unfortunately i get this error now.

```
E/flutter (  787): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument: is a regular instance: Instance of 'LocationDto'
E/flutter (  787): #0      _SendPort._sendInternal (dart:isolate-patch/isolate_patch.dart:249:43)
E/flutter (  787): #1      _SendPort.send (dart:isolate-patch/isolate_patch.dart:230:5)
E/flutter (  787): #2      LocationServiceRepository.callback (package:drivers_app/tabPages/location_service_reposirtory.dart:58:11)
E/flutter (  787): <asynchronous suspension>
E/flutter (  787): #3      LocationCallbackHandler.callback (package:drivers_app/tabPages/LocationCallbackHandler.dart:24:5)
E/flutter (  787): <asynchronous suspension>
```

The issue lies here 
```
class LocationServiceRepository {
....
Future<void> callback(LocationDto locationDto) async {
    print('$_count location in dart: ${locationDto.toString()}');
    await setLogPosition(_count, locationDto);
    final SendPort? send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(locationDto); //here
    _count++;
  }
```
what is causing this and how can i fix it ?

**Comment by jesussmile** [comment]
i tried to update it with 
```ruby
 @pragma('vm:entry-point')
  Future<void> callback(LocationDto locationDto) async {
    print('$_count location in dart: ${locationDto.toString()}');
    await setLogPosition(_count, locationDto);
    final SendPort? send = IsolateNameServer.lookupPortByName(isolateName);
    send?.send(locationDto);
    _count++;
  }
```
still the same error

**Comment by sanak** [comment]
Hi @jesussmile
Could you try my pull request (#53) fork branch, once ?
(Because the error location is same as my fix.)

**Comment by jesussmile** [comment]
hi @sanak 
I tried your fix but it still keeps getting me the same error,
so, I created a small project with the recent updated in gradle, flutter etc. and used your fix. please check it if its working on your side ?

[https://github.com/jesussmile/bg_github_error](url)

**Comment by jesussmile** [comment]
Yes! works fine. thank you

**Comment by sanak** [comment]
@jesussmile Okay, thanks for confirmation!

**Comment by Strafe0** [comment]
@sanak, I have the same error, but your PR doesn't work for me.

**Comment by Yukams** [comment]
PR is merged, closing this issue, please open your own ticket and eventually push your own PR please so we can keep track of it @Strafe0 thanks !
