### ISSUE TITLE
Erro null safety

### ISSUE THREAD

**Issue by Raphael-Jose-Ferraro-IRForever** [Yukams/background_locator_fixed#63]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8512): #0      SettingsUtil._getCommonArgumentsMap (package:background_locator_2/utils/settings_util.dart:39:54)
E/flutter ( 8512): #1      SettingsUtil.getArgumentsMap (package:background_locator_2/utils/settings_util.dart:17:18)
E/flutter ( 8512): #2      BackgroundLocator.registerLocationUpdate (package:background_locator_2/background_locator.dart:39:31)

**Comment by jabguru** [comment]
I have this same error @Yukams 
Both on Android and iOS
