### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by DBC201** [Yukams/background_locator_fixed#68]
When I try to build and run, my app crashes with the following error:

```
E/AndroidRuntime(10738): java.lang.RuntimeException: Unable to create service yukams.app.background_locator_2.IsolateHolderService: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()'
E/AndroidRuntime(10738): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4498)
E/AndroidRuntime(10738): 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
E/AndroidRuntime(10738): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2161)
E/AndroidRuntime(10738): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(10738): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(10738): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(10738): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(10738): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10738): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(10738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(10738): Caused by: java.lang.NullPointerException: Attempt to read from field 'java.lang.String io.flutter.view.FlutterCallbackInformation.callbackLibraryPath' on a null object reference in method 'java.lang.String io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString()'
E/AndroidRuntime(10738): 	at io.flutter.embedding.engine.dart.DartExecutor$DartCallback.toString(DartExecutor.java:421)
E/AndroidRuntime(10738): 	at java.lang.String.valueOf(String.java:3657)
E/AndroidRuntime(10738): 	at java.lang.StringBuilder.append(StringBuilder.java:132)
E/AndroidRuntime(10738): 	at io.flutter.embedding.engine.dart.DartExecutor.executeDartCallback(DartExecutor.java:175)
E/AndroidRuntime(10738): 	at yukams.app.background_locator_2.IsolateHolderExtensionKt.startLocatorService(IsolateHolderExtension.kt:51)
E/AndroidRuntime(10738): 	at yukams.app.background_locator_2.IsolateHolderService.onCreate(IsolateHolderService.kt:83)
E/AndroidRuntime(10738): 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4485)
E/AndroidRuntime(10738): 	... 9 more
I/Process (10738): Sending signal. PID: 10738 SIG: 9
```

**Comment by DBC201** [comment]
Calling 
```await BackgroundLocator.initialize();```
before registering solved the issue.
