### ISSUE TITLE
Android crash when start Locator

### ISSUE THREAD

**Issue by Hosamkawkgy** [Yukams/background_locator_fixed#76]
Things were fine in the old version, I never had this problem. Is there any update on this?
Or keep the old version for the time being until we get the latest updates ؟!

 java.lang.IncompatibleClassChangeError: Found class com.google.android.gms.location.FusedLocationProviderClient, but interface was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~QL_sEP8t1Imcgq67YGeu4A==/com.example-We0cUMLjtzq133zZW0GvZA==/base.apk)
 	at yukams.app.background_locator_2.provider.GoogleLocationProviderClient.requestLocationUpdates(GoogleLocationProviderClient.kt:17)
 	at yukams.app.background_locator_2.IsolateHolderService.startHolderService(IsolateHolderService.kt:199)
 	at yukams.app.background_locator_2.IsolateHolderService.onStartCommand(IsolateHolderService.kt:166)
 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4424)
 	at android.app.ActivityThread.access$2000(ActivityThread.java:257)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
 	at android.os.Handler.dispatchMessage(Handler.java:106)
 	at android.os.Looper.loop(Looper.java:236)
 	at android.app.ActivityThread.main(ActivityThread.java:8037)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)

**Comment by tulioccalazans** [comment]
I think v2.0.6 (latest version - [PR](https://github.com/Yukams/background_locator_fixed/pull/70)) fix this issue.

**Comment by osirislpzJelp** [comment]
I have a same error

Flutter 3.3.4
Dart 2.18.2
background_locator_2: 2.0.6

```
E/AndroidRuntime(28248): java.lang.IncompatibleClassChangeError: Found interface com.google.android.gms.location.FusedLocationProviderClient, but class was expected (declaration of 'com.google.android.gms.location.FusedLocationProviderClient' appears in /data/app/~~C2mCnX2phgewp7MhUJ57sA==/<id>==/base.apk)
E/AndroidRuntime(28248): 	at com.lyokone.location.FlutterLocation.createLocationCallback(FlutterLocation.java:219)
E/AndroidRuntime(28248): 	at com.lyokone.location.FlutterLocation.changeSettings(FlutterLocation.java:197)
E/AndroidRuntime(28248): 	at com.lyokone.location.MethodCallHandlerImpl.onChangeSettings(MethodCallHandlerImpl.java:106)
E/AndroidRuntime(28248): 	at com.lyokone.location.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:40)
E/AndroidRuntime(28248): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/AndroidRuntime(28248): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/AndroidRuntime(28248): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/AndroidRuntime(28248): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/AndroidRuntime(28248): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(28248): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(28248): 	at android.os.Looper.loopOnce(Looper.java:226)
E/AndroidRuntime(28248): 	at android.os.Looper.loop(Looper.java:313)
E/AndroidRuntime(28248): 	at android.app.ActivityThread.main(ActivityThread.java:8663)
E/AndroidRuntime(28248): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(28248): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
E/AndroidRuntime(28248): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
I/Process (28248): Sending signal. PID: 28248 SIG: 9
```
