### ISSUE TITLE
the callback function is not executed in registerLocationUpdate and i am not getting the locationDto object 

### ISSUE THREAD

**Issue by Hassab-noudjoud** [Yukams/background_locator_fixed#95]

**Comment by Hassab-noudjoud** [comment]
for more details sometimes it get this error: 
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (10020): #0      SettingsUtil._getCommonArgumentsMap (package:background_locator_2/utils/settings_util.dart:39:54)
E/flutter (10020): #1      SettingsUtil.getArgumentsMap (package:background_locator_2/utils/settings_util.dart:17:18)
E/flutter (10020): #2      BackgroundLocator.registerLocationUpdate (package:background_locator_2/background_locator.dart:39:31)

**Comment by Hassab-noudjoud** [comment]
the problem is here in line 39
and the call back function is not called even when using @Pragma

<img width="559" alt="image" src="https://github.com/Yukams/background_locator_fixed/assets/57769058/01f71b60-2b57-4bc7-b654-a39eb03c5b1b">

**Comment by stingrayx** [comment]
@Hassab-noudjoud do you use "compileSdkVersion: 33" as well? Did you find any further hint or possibility to get it working again? Thanks

**Comment by Hassab-noudjoud** [comment]
yes i'am using compileSdkVersion: 33, and i'm still facing the same issue
